"""init

Revision ID: bd79289578b0
Revises: 
Create Date: 2024-09-11 07:25:11.114726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd79289578b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_category', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category'], ['categories.id'], name=op.f('fk_categories_parent_category_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_index(op.f('ix_categories_parent_category'), 'categories', ['parent_category'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index(op.f('ix_tickets_email'), 'tickets', ['email'], unique=False)
    op.create_index(op.f('ix_tickets_name'), 'tickets', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('rule', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('has_subscription_fee', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_users_phone_number'))
    )
    op.create_table('advertisements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('video', sa.String(length=255), nullable=True),
    sa.Column('hour_price', sa.Numeric(), nullable=True),
    sa.Column('day_price', sa.Numeric(), nullable=True),
    sa.Column('week_price', sa.Numeric(), nullable=True),
    sa.Column('month_price', sa.Numeric(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_advertisements_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_advertisements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advertisements'))
    )
    op.create_index(op.f('ix_advertisements_category_id'), 'advertisements', ['category_id'], unique=False)
    op.create_index(op.f('ix_advertisements_title'), 'advertisements', ['title'], unique=False)
    op.create_index(op.f('ix_advertisements_user_id'), 'advertisements', ['user_id'], unique=False)
    op.create_table('advertisement_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('advertisement_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], name=op.f('fk_advertisement_images_advertisement_id_advertisements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advertisement_images'))
    )
    op.create_index(op.f('ix_advertisement_images_advertisement_id'), 'advertisement_images', ['advertisement_id'], unique=False)
    op.create_table('calendars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('advertisement_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], name=op.f('fk_calendars_advertisement_id_advertisements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendars')),
    sa.UniqueConstraint('advertisement_id', 'day', name=op.f('uq_calendars_advertisement_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendars')
    op.drop_index(op.f('ix_advertisement_images_advertisement_id'), table_name='advertisement_images')
    op.drop_table('advertisement_images')
    op.drop_index(op.f('ix_advertisements_user_id'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_title'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_category_id'), table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_table('users')
    op.drop_index(op.f('ix_tickets_name'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_email'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_categories_parent_category'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
